import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execFileSync } from 'node:child_process';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'closure-check-'));

try {
  // 1. Run npm pack --pack-destination <tmpdir>
  execFileSync('npm', ['pack', '--pack-destination', tmpDir], {
    cwd: rootDir,
    stdio: 'pipe',
  });

  // 2. Find tarball
  const files = fs.readdirSync(tmpDir);
  const tarball = files.find((f) => f.endsWith('.tgz'));
  assert(tarball, 'No tarball generated by npm pack');

  // 3. Extract tarball
  const tarballPath = path.join(tmpDir, tarball);
  execFileSync('tar', ['-xzf', tarballPath, '-C', tmpDir], {
    stdio: 'pipe',
  });

  const pkgDir = path.join(tmpDir, 'package');
  assert(fs.existsSync(pkgDir), 'Extracted package directory does not exist');

  // 4. Assert PRESENT:
  // package/package.json, package/contract/defaults.json, package/contract/index.mjs, package/extension/src/manifest.json
  const requiredFiles = [
    'package.json',
    path.join('contract', 'defaults.json'),
    path.join('contract', 'index.mjs'),
    path.join('extension', 'src', 'manifest.json'),
  ];
  for (const rel of requiredFiles) {
    const p = path.join(pkgDir, rel);
    assert(fs.existsSync(p), `Required file missing from package: ${rel}`);
  }

  // 5. Assert ABSENT:
  // extension/dist, any *.pem / *.key / .env*
  assert(
    !fs.existsSync(path.join(pkgDir, 'extension', 'dist')),
    'extension/dist must NOT be present in package'
  );

  function checkDisallowedRecursive(dir) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        assert(
          entry.name !== 'dist' || !full.includes(path.join('extension', 'dist')),
          `extension/dist found in package: ${full}`
        );
        checkDisallowedRecursive(full);
      } else {
        const name = entry.name;
        assert(!name.endsWith('.pem'), `Disallowed *.pem found: ${full}`);
        assert(!name.endsWith('.key'), `Disallowed *.key found: ${full}`);
        assert(!name.startsWith('.env'), `Disallowed .env* found: ${full}`);
      }
    }
  }
  checkDisallowedRecursive(pkgDir);

  // 6. From extracted dir, run a Node import of contract/index.mjs
  execFileSync(
    process.execPath,
    [
      '-e',
      `import('./contract/index.mjs').then(m => {
        if (!m.CONTRACT_VERSION || !m.defaults || !m.contractDir || !m.schemaDir) {
          console.error('Missing expected exports in contract/index.mjs');
          process.exit(1);
        }
      })`,
    ],
    {
      cwd: pkgDir,
      stdio: 'inherit',
    }
  );

  console.log('CLOSURE_OK');
} finally {
  fs.rmSync(tmpDir, { recursive: true, force: true });
}
